### ISSUE TITLE
MESSAGE_CREATE example causes unhandled error

### ISSUE THREAD

**Issue by quorauk** [DjDeveloperr/RPCord#2]
Hey,

I am trying out this library to see if its possible to subscribe to the START_SPEAKING event in discord rpc.

I'm trying the code example in readme.md for subscribing to the MESSAGE_CREATE event. When I run it I get a popup window from discord to authorize the oauth request, I hit authorize and get the following error in the console

```
events.js:367
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  code: 5000,
  message: 'OAuth2 Error: invalid_scope: The requested scope is invalid, unknown, or malformed.'
})
    at RPClient.emit (events.js:365:17)
    at RPClient.processPacket (C:\Users\max\Documents\DiscordNode\node_modules\rpcord\dist\client.js:46:26)
    at DiscordIPC.<anonymous> (C:\Users\max\Documents\DiscordNode\node_modules\rpcord\dist\client.js:34:48)
    at DiscordIPC.emit (events.js:376:20)
    at Socket.<anonymous> (C:\Users\max\Documents\DiscordNode\node_modules\rpcord\dist\ipc.js:33:22)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    code: 5000,
    message: 'OAuth2 Error: invalid_scope: The requested scope is invalid, unknown, or malformed.'
  }
}
```

Is there something I am missing here? Do I need to handle an oauth redirect somewhere or do I need my app to be approved by discord to use the rpc scope?

Thanks!

**Comment by quorauk** [comment]
Happy to close this issue now, strangely this didn't work with an application in a team, but does on a personal application.  Very strange!

**Comment by DjDeveloperr** [comment]
I had faced same issue while developing. For some reason, you have to whitelist yourself even if you own the team which the application is in.
